name: Post release actions
on: workflow_call

jobs:
  Pre_Release_Actions:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update galaxy.yml with the new release version
        run: |
          version="$release_name"
          sed -i 's/[1-9]\?[0-9]\.[1-9]\?[0-9]\.[1-9]\?[0-9]/'"${version:1}"'/' galaxy.yml

      - name: Commit and push changes to galaxy.yml
        run: |
          git config --global user.name "Github action BOT"
          git commit -am "Automated commit to update galaxy.yml"
          git push
