name: Release Drafter
on:
  workflow_call:
    inputs:
      labeler:
        type: boolean
        description: 'Only label PR'
        required: true
        default: true

jobs:
  Release_Drafter:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MY_PAT }}
    steps:
      - name: Label pull request
        if: ${{ github.event.inputs.labeler }}
        uses: release-drafter/release-drafter@v5
        with:
          disable-releaser: true
          disable-autolabeler: false

      - name: Update release draft
        if: not ${{ github.event.inputs.labeler }}
        uses: release-drafter/release-drafter@v5
        with:
          publish: true
          disable-releaser: false
          disable-autolabeler: true
