name: Release Drafter
on: workflow_call

jobs:
  Release_Drafter:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Label pull request
        if: github.event_name == 'pull_request'
        uses: release-drafter/release-drafter@v5
        with:
          disable-releaser: true
          disable-autolabeler: false

      - name: Update release draft
        if: github.event_name == 'push'
        uses: release-drafter/release-drafter@v5
        with:
          publish: true
          disable-releaser: false
          disable-autolabeler: true
