name: Release Drafter
on:
  workflow_call:
    inputs:
      is_collection:
        type: boolean
        required: false
        default: false
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Release_Drafter_Labeler:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Label pull request
        uses: release-drafter/release-drafter@v5
        with:
          disable-releaser: true
          disable-autolabeler: false

  Release_Draft:
    if: ${{ github.event_name }} == 'push' && ${{ github.event.inputs.is_collection == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create new release
        uses: release-drafter/release-drafter@v5
        with:
          publish: true
          disable-releaser: false
          disable-autolabeler: true

  Release_Draft_Collection:
    if: ${{ github.event_name }} == 'push' && ${{ github.event.inputs.is_collection == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get new release tag name
        id: release_name
        uses: release-drafter/release-drafter@v5
        with:
          disable-releaser: false
          disable-autolabeler: true

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update galaxy.yml with the new release version
        run: |
          version="${{ steps.release_name.outputs.name }}"
          sed -i 's/[1-9]\?[0-9]\.[1-9]\?[0-9]\.[1-9]\?[0-9]/'"${version:1}"'/' galaxy.yml

      - name: Commit and push changes to galaxy.yml
        run: |
          git config --global user.name "Github action BOT"
          git config --global user.email "BOT@users.noreply.github.com"
          git commit -am "Automated commit to update galaxy.yml"
          git push

      - name: Create new release
        uses: release-drafter/release-drafter@v5
        with:
          publish: true
          disable-releaser: false
          disable-autolabeler: true