name: Release Drafter
on: workflow_call
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Release_Drafter_Labeler:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Label pull request
        uses: release-drafter/release-drafter@v5
        with:
          config-name: VincePayeur/GithubAction/.github/release-drafter.yml@main
          disable-releaser: true
          disable-autolabeler: false

  Get_Draft_Name:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      release_name: ${{ steps.release_name.outputs.name }}
    steps:
      - name: Get new release tag name
        id: release_name
        uses: release-drafter/release-drafter@v5
        with:
          disable-releaser: false
          disable-autolabeler: true

  Update_galaxy_file:
    needs: Get_Draft_Name
    runs-on: ubuntu-latest
    env:
      release_name: ${{ needs.Get_Draft_Name.outputs.release_name }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update galaxy.yml with the new release version
        run: |
          version="$release_name"
          sed -i 's/[1-9]\?[0-9]\.[1-9]\?[0-9]\.[1-9]\?[0-9]/'"${version:1}"'/' galaxy.yml

      - name: Commit and push changes to galaxy.yml
        run: |
          git config --global user.name "Github action BOT"
          git commit -am "Automated commit to update galaxy.yml"
          git push

  Release_Draft:
    needs: Update_galaxy_file
    runs-on: ubuntu-latest
    steps:
      - name: Create new release
        uses: release-drafter/release-drafter@v5
        with:
          publish: true
          disable-releaser: false
          disable-autolabeler: true
