name: Release Drafter
on: workflow_dispatch

jobs:
  Release_Drafter:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get tag name
        id: tag_name
        uses: release-drafter/release-drafter@v5
        with:
            disable-releaser: true
            disable-autolabeler: true