name: Test
on: workflow_dispatch

jobs:
  Release_Drafter:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get tag name
        id: tag_name
        uses: release-drafter/release-drafter@v5
        with:
          disable-releaser: false
          disable-autolabeler: true

      - name: Print tag name
        run: |
          echo "--- Start ---"
          echo "${{ steps.tag_name.outputs.tag_name }}"
          echo "--- End ---"